### PR TITLE
arch README: fix repo url

### PR DESCRIPTION
**Pull request by irega**
Hi!

This PR seems to be not useful,  but after I wasted 1 hour trying to install the package, I think it can be useful for someone. 

My error was I was following the installation notes from README to install the package in my Manjaro system. The problem is the repo url was pointing to the old fork which have some errors in the installation.

This PR fixes the repo url, removes some deprecated text from the author and applies some markdown styles.

Greetings!

### CODE REVIEW

**Comment by irega** [comment]
@thopiekar it's ready for review (sorry but I can't add you as reviewer, probably I don't have permission :D)

**Comment by thopiekar** [comment]
Even if it is "only" on documentation, it is valueable effort.
Many thanks for your work and taking time!

Something we could do is moving all the instructions to the main /README.md.
Can't remember when I approved the creation of this file, but I don't think we need a separate file for installation instructions for ArchLinux*. The README.md is not that large that we need to split it at the moment.

Therefore I think of the following to-dos:
 [ ] Adding a section around the Ubuntu/Debian instructions in ./README.md
 [ ] Moving Arch instructions to ./README.md
 [ ] (optionally!) Adding formatting to other code blocks in ./README.md

If it doesn't take too much time for you, I would be glad to see the changes made here. Otherwise (since the mess is already there) keep it like it and I'll merge it! :wink:

**Comment by irega** [comment]
> See above

done!

**Comment by thopiekar** [comment]
Really nice! Many thanks for the efforts and taking time!

**Pull request merged**
